version: '3.8'

services:
  # Backend API with SQLite persistence
  backend:
    build: ./backend
    container_name: traffic_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:///./data/traffic_management.db
      SECRET_KEY: your-super-secret-jwt-key-here-change-in-production
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    volumes:
      # CRITICAL: Mount SQLite database to persistent volume
      - sqlite_data:/app/data
      - ./backend:/app  # For development hot-reload
    networks:
      - traffic_network

  # Frontend
  frontend:
    build: ./frontend
    container_name: traffic_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    networks:
      - traffic_network

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: traffic_nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - traffic_network
    profiles:
      - production

# CRITICAL: Define persistent volume for SQLite database
volumes:
  sqlite_data:
    driver: local

networks:
  traffic_network:
    driver: bridge
