version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: traffic_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: traffic_management
      MYSQL_USER: traffic_user
      MYSQL_PASSWORD: traffic_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - traffic_network

  # Backend API
  backend:
    build: ./backend
    container_name: traffic_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql+pymysql://traffic_user:traffic_password@db:3306/traffic_management
      SECRET_KEY: your-super-secret-jwt-key-here-change-in-production
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - traffic_network

  # Frontend
  frontend:
    build: ./frontend
    container_name: traffic_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    networks:
      - traffic_network

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: traffic_nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - traffic_network
    profiles:
      - production

volumes:
  mysql_data:

networks:
  traffic_network:
    driver: bridge
