name: traffic-management-backend
runtime: python3.11
framework: fastapi
build:
  command: pip install -r requirements.txt
start:
  command: python -m uvicorn your_app.wsgi:app --host 0.0.0.0 --port 8000
port: 8000
healthcheck:
  path: /health
env:
  ENVIRONMENT: production
  PYTHONPATH: /app
