[build]
command = "pip install -r requirements.txt"

[deploy]
command = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
port = 8000

[service]
name = "traffic-management-backend"
runtime = "python3.11"

[healthcheck]
path = "/health"
method = "GET"

[environment]
ENVIRONMENT = "production"
PYTHONPATH = "/app/backend"
