# Leapcell PostgreSQL Deployment Configuration
# This file configures the deployment with PostgreSQL database

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: traffic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: traffic_management
      POSTGRES_USER: traffic_user
      POSTGRES_PASSWORD: traffic_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traffic_user -d traffic_management"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: .
    container_name: traffic_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://traffic_user:traffic_password@postgres:5432/traffic_management
      SECRET_KEY: your-super-secret-jwt-key-here-change-in-production
      ENVIRONMENT: production
      CORS_ORIGINS: "*"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  traffic_network:
    driver: bridge
