name: traffic-management-backend
runtime: python3.11
build:
  command: bash build.sh
start:
  command: python app.py
port: 8000
healthcheck:
  path: /health
env:
  ENVIRONMENT: production
  PYTHONPATH: /app
