[build]
builder = "python"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"

[services.main]
name = "traffic-management-backend"

[services.main.env]
NODE_ENV = "production"

[services.database]
name = "traffic-management-db"

[services.database.env]
MYSQL_ROOT_PASSWORD = "${{ MYSQL_ROOT_PASSWORD }}"
MYSQL_DATABASE = "traffic_management"
MYSQL_USER = "traffic_user"
MYSQL_PASSWORD = "${{ MYSQL_PASSWORD }}"
