"""Add no parking zones table

Revision ID: 1e102fe3cb1b
Revises: 
Create Date: 2025-08-22 10:24:30.009377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e102fe3cb1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_parking_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('restriction_reason', sa.String(length=100), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('is_strict', sa.Boolean(), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('enforcement_hours', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_no_parking_zones_id'), 'no_parking_zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_no_parking_zones_id'), table_name='no_parking_zones')
    op.drop_table('no_parking_zones')
    # ### end Alembic commands ###
