"""add_incident_prone_areas_table

Revision ID: f558f3bc38dc
Revises: 1e102fe3cb1b
Create Date: 2025-08-27 04:32:12.398375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f558f3bc38dc'
down_revision = '1e102fe3cb1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_prone_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('area_type', sa.Enum('ACCIDENT_PRONE', 'CRIME_HOTSPOT', 'FLOOD_PRONE', 'TRAFFIC_CONGESTION', 'ROAD_HAZARD', name='incidentproneareatype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('affected_roads', sa.JSON(), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('last_incident_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_hours', sa.JSON(), nullable=True),
    sa.Column('common_incident_types', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('prevention_measures', sa.Text(), nullable=True),
    sa.Column('alternative_routes', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_prone_areas_id'), 'incident_prone_areas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_prone_areas_id'), table_name='incident_prone_areas')
    op.drop_table('incident_prone_areas')
    # ### end Alembic commands ###
